source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks'
gem "carrierwave", "~> 0.10.0"
gem 'fog'
gem 'dotenv-rails'
gem 'mini_magick'
gem 'net-ssh'
gem 'bcrypt', '~> 3.1.7'
group :development, :test do
  gem 'byebug'
  gem "guard-rspec"
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
