# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f67ec363de26f14fe7def322625c152ad630944faa8abe4a3765b5b21a716a74d5eb602cc05e75df74a3225c27f524fa0fd11c389ddac0152d65930d0f7907

test:
  secret_key_base: 6b9bc215911b494189167706163701eee741e29d48a5b4e230bfe730f1d24d52a33a6359cf858305e3a60a899d4118394b469ea8eea7e73cc844697eba377e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
