# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b083d095865f14c1ad0129a75e2a27fa47ed03a94d8604e4627ac66e4d4fba62550e733a5b5aeef6721de2671e4040ab573448d0a096c0a0a42c74e29adb73fc

test:
  secret_key_base: 07a0f58e367fe37a1d0cdbb5fd0d7d7e1a005f651d615fd5e16c81a7c49558432997b2eb0563106660b09c56bb2626804627361372ca0f5320f64cae101463e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
